package com.demo.entities;
// Generated Feb 23, 2024, 1:06:06 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;


import jakarta.persistence.*;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "pento_sm4")
public class Account implements java.io.Serializable {

	private Integer id;
	private Role role;
	private String email;
	private String password;
	private String status;
	private String securityCode;
	private Set<Reviews> reviewses = new HashSet<Reviews>(0);
	private Set<User> users = new HashSet<User>(0);

	public Account() {
	}

	public Account(Role role, String email, String password, String status, String securityCode) {
		this.role = role;
		this.email = email;
		this.password = password;
		this.status = status;
		this.securityCode = securityCode;
	}

	public Account(Role role, String email, String password, String status, String securityCode, Set<Reviews> reviewses,
			Set<User> users) {
		this.role = role;
		this.email = email;
		this.password = password;
		this.status = status;
		this.securityCode = securityCode;
		this.reviewses = reviewses;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "security_code", nullable = true, length = 250)
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Reviews> getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set<Reviews> reviewses) {
		this.reviewses = reviewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
