package com.demo.entities;
// Generated Feb 23, 2024, 1:06:06 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "pento_sm4")
public class Menu implements java.io.Serializable {

	private Integer id;
	private Images images;
	private String name;
	private String description;
	private double price;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	private Set<Ratings> ratingses = new HashSet<Ratings>(0);

	public Menu() {
	}

	public Menu(String name, double price) {
		this.name = name;
		this.price = price;
	}

	public Menu(Images images, String name, String description, double price, Set<OrderDetail> orderDetails,
			Set<Ratings> ratingses) {
		this.images = images;
		this.name = name;
		this.description = description;
		this.price = price;
		this.orderDetails = orderDetails;
		this.ratingses = ratingses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id")
	public Images getImages() {
		return this.images;
	}

	public void setImages(Images images) {
		this.images = images;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Ratings> getRatingses() {
		return this.ratingses;
	}

	public void setRatingses(Set<Ratings> ratingses) {
		this.ratingses = ratingses;
	}

}
