package com.demo.entities;
// Generated Feb 1, 2024, 10:59:46 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * TableType generated by hbm2java
 */
@Entity
@Table(name = "table_type", catalog = "pento_sm4")
public class TableType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String location;
	private Set<Tables> tableses = new HashSet<Tables>(0);

	public TableType() {
	}

	public TableType(String name, String location) {
		this.name = name;
		this.location = location;
	}

	public TableType(String name, String location, Set<Tables> tableses) {
		this.name = name;
		this.location = location;
		this.tableses = tableses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", nullable = false, length = 250)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tableType")
	public Set<Tables> getTableses() {
		return this.tableses;
	}

	public void setTableses(Set<Tables> tableses) {
		this.tableses = tableses;
	}

}
