package com.demo.entities;
// Generated Feb 1, 2024, 10:59:46 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Tables generated by hbm2java
 */
@Entity
@Table(name = "tables", catalog = "pento_sm4")
public class Tables implements java.io.Serializable {

	private Integer id;
	private Branchs branchs;
	private TableType tableType;
	private String name;
	private int numberOfSeat;
	private String status;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Tables() {
	}

	public Tables(String name, int numberOfSeat, String status) {
		this.name = name;
		this.numberOfSeat = numberOfSeat;
		this.status = status;
	}

	public Tables(Branchs branchs, TableType tableType, String name, int numberOfSeat, String status,
			Set<Orders> orderses) {
		this.branchs = branchs;
		this.tableType = tableType;
		this.name = name;
		this.numberOfSeat = numberOfSeat;
		this.status = status;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branchs getBranchs() {
		return this.branchs;
	}

	public void setBranchs(Branchs branchs) {
		this.branchs = branchs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "table_type_id")
	public TableType getTableType() {
		return this.tableType;
	}

	public void setTableType(TableType tableType) {
		this.tableType = tableType;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "number_of_seat", nullable = false)
	public int getNumberOfSeat() {
		return this.numberOfSeat;
	}

	public void setNumberOfSeat(int numberOfSeat) {
		this.numberOfSeat = numberOfSeat;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tables")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
